In [1]:
import numpy as np
import pandas as pd


**2 Neuronet**

In [9]:
path = input()
data = pd.read_csv(path, sep = '\s+', dtype = np.float64, header = None)

/home/rita/Downloads/Python2021/test203.txt


In [10]:
print(data)

     0    1    2
0  0.1  0.0  0.0
1  0.0  0.1  0.0
2  0.0  0.0  0.1


In [16]:
data2 = data**2

In [17]:
data2

0     1     2
0  0.01  0.00  0.00
1  0.00  0.01  0.00
2  0.00  0.00  0.01

In [18]:
pathb = input()
vector = pd.read_csv(pathb, sep = '\s+', dtype = np.float64, header = None)

/home/rita/Downloads/Python2021/testb203.txt


In [22]:
x = np.array(list(map(float, input().split())))

0.5 0.1 0.5


In [24]:
print(np.shape(x), np.shape(vector), np.shape(data2))

(3,) (1, 3) (3, 3)


In [26]:
answer = vector @ (data2 @ x )

In [28]:
answer

0    0.0275
dtype: float64

**3 Gamestats**


In [33]:
games = pd.read_csv('./games001.csv', sep = ';')
rates = pd.read_csv('./rates001.csv', sep = ';')

In [34]:
games

id             name           company
0   1           XCOM 2           Firaxis
1   2   Civilization V           Firaxis
2   3  Darkest Dungeon  Red Hook Studios
3   4     Star Traders    Trese Brothers

In [35]:
rates

id  mark
0    1     8
1    1     9
2    1    10
3    1     9
4    1     8
5    1     8
6    1     8
7    1    10
8    1     9
9    1    10
10   1     9
11   1     9
12   1     7
13   1     9
14   1    10
15   2     8
16   2     9
17   2     7
18   2     8
19   2    10
20   2     8
21   2     9
22   2     8
23   2     9
24   2    10
25   2     7
26   2     7
27   3    10
28   3     7
29   3    10
30   3    10
31   3     8
32   4     7
33   4     9
34   4     8
35   4     8

In [41]:
score = []
for i in games["id"]:
    i = int(i)
    score.append((sum(rates[rates["id"] == i]["mark"]))/len(rates[rates["id"] == i]))
    
    
print(score)

[8.866666666666667, 8.333333333333334, 9.0, 8.0]


In [45]:
games["score"] = score

In [46]:
games["score"] = round(games["score"], 3)

In [52]:
games = games.sort_values('score', ascending=False)

In [74]:
gamestop3 = games.iloc[:3]
gamestop3

id             name           company  score
2   3  Darkest Dungeon  Red Hook Studios  9.000
0   1           XCOM 2           Firaxis  8.867
1   2   Civilization V           Firaxis  8.333

In [151]:
answer = pd.concat([gamestop3["name"], gamestop3["score"]], axis = 1)

In [140]:
answer.reset_index()

index             name  score
0      2  Darkest Dungeon  9.000
1      0           XCOM 2  8.867
2      1   Civilization V  8.333

In [102]:
topcompany = gamestop3.groupby('company').count()
topcompany = topcompany.sort_values('score', ascending = False)
topcompany_name = topcompany.index[0]


In [108]:
number_of_games = topcompany.loc[topcompany_name, "score"]

In [103]:
topcompany_name

'Firaxis'

In [150]:

dictt = {"name" : [topcompany_name], "score" : [int(number_of_games)]}
top1 = pd.DataFrame(data = dictt)

In [153]:
answer = pd.concat([answer, top1], axis = 0)


In [155]:
answer.columns = [0,1]
answer

0      1
2  Darkest Dungeon  9.000
0           XCOM 2  8.867
1   Civilization V  8.333
0          Firaxis  2.000

**4 Hirsh**

не получилось


In [160]:
papers = pd.read_csv('./papers001.csv', sep = ';')
links = pd.read_csv('./links001.csv', sep = ';', names = ['id', 'reference'])

In [162]:
links = links.iloc[1:]

In [163]:
links

id       reference
1  1       Title Two
2  1     Title Three
3  1  Something Else
4  1        Offtopic
5  2     Title Three
6  2      Title Four
7  2  One More Paper
8  3             Foo
9  4             Bar

In [159]:
papers

id        title    author
0   1    Title One    Ivanov
1   2    Title Two   Sidorov
2   3  Title Three    Petrov
3   4   Title Four  A.N.Onim
4   5   Title Five    Petrov
5   6    Title Six    Petrov
6   7  Title Seven   Sidorov

**1 ocean**

In [167]:
N, M = map( int, input().split() )


4 6


In [174]:
data = [np.array( input().split() , dtype = int) for i in range(N)]


1 4 4 2 1 1
0 0 1 0 -1 -1
-2  -3  -1  -5 -6 -4
-1 -3 -3 -4 -4 -2


In [175]:
data

[array([1, 4, 4, 2, 1, 1]),
 array([ 0,  0,  1,  0, -1, -1]),
 array([-2, -3, -1, -5, -6, -4]),
 array([-1, -3, -3, -4, -4, -2])]

In [176]:
df_map = pd.DataFrame(data)

df_map

0  1  2  3  4  5
0  1  4  4  2  1  1
1  0  0  1  0 -1 -1
2 -2 -3 -1 -5 -6 -4
3 -1 -3 -3 -4 -4 -2


    1 общую площадь клеточек моря, в которых его глубина больше 5;
    2 общий объём всей воды на карте;
    3 максимальную высоту над уровнем моря, которая есть на этой карте.


In [177]:
first = ((df_map < -5).astype(int)).values.sum()
first

1

In [178]:
second = df_map[df_map < 0].fillna(0).values.sum()
second = int(second)*(-1)
second

40

In [180]:
third = df_map.values.max()
third

4